{% set name = "pyxem" %}
{% set version = "0.8.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8fc9d875e4cdf502eb50ed288af17af90a5c563d0fa4622209d70cca730b7d5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3
  run:
    - python >=3
    - hyperspy >1.2
    - scikit-image <0.15
    - matplotlib <3.1.0
    - scikit-learn >=0.19
    - transforms3d
    - diffpy.structure

test:
  requires:
    - pytest
  imports:
    - pyxem
    - pyxem.utils
    - pyxem.io_plugins
    - pyxem.components
    - pyxem.generators
    - pyxem.signals
    - pyxem.libraries
  commands:
    - pytest --pyargs pyxem

about:
  home: https://github.com/pyxem/pyxem
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: An open-source Python library for crystallographic electron microscopy
  doc_url: http://pyxem.github.io/pyxem/

extra:
  recipe-maintainers:
    - tschoonj
    - dnjohnstone
