travis:
  secure:
    BINSTAR_TOKEN: MUsAzmjfLhBjItoH/8XYGlVF9r2cfVih3L1Jb1YHai/UwtZYNQx9NZgvUag0j8UsanWSL2eSPssCplY6Jaedrx5EiOh7kVEK6PpmoqtDlklwgXvGz0abbbS04BT1TvDn4ypYOwh5pg2BrkbTGqcBP5vletyK+3mGO/SWeVu+XB9YWOYDwD6c9jyguYWHPomyJnc+Okp9JMhuhzRW7VxwPkzTGtH2UJar9wpOZxixIGHadEWWFLxCwoLf6DHbULwy8Isj9zYma6v6WISZHz87WWn7EEIbI0L4WhRIVI7xjUT1MECblvZp5IP7oFeLvo/SoQ7tQuoemrzptetbLjceWsRjZPsaefxqNgImX47DXJvLa+MCoIos+sDmX1GyM3+6xUtmHbBnsummnj7enY9ljuIZh2Os9ALJwTtJTf0Lk6vp6gn4QI5jNLrNVH/jTmnb/rNKfwJgIIrdGO6HFl34gfb2j3+y5q6PpwqIWzhNEgcXHdppiEHHmjwmQRDDLqKv1qGCGil0fOVqh5BCiVYIXBiGMlB2BGsgnoZj/S1o3mLThda0XDQlfZfYRsrRw4tHFcDNEkDka19k8ruYgwlL/xqk/I/N45MGtmXjfQAmWDF65/Z1RznycGy5whZPLVGtMgtd46DaWNzYzGQogUXIIPNOG8iwBdaLoUuM4OtQwe4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
